package cli

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/spf13/cobra"
)

const defaultSkillDescription = "Skill generated by agentcom"

var skillNamePattern = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

type skillTarget struct {
	Agent string `json:"agent"`
	Path  string `json:"path"`
}

type skillValidationReport struct {
	Path   string   `json:"path"`
	Status string   `json:"status"`
	Checks []string `json:"checks,omitempty"`
	Issues []string `json:"issues,omitempty"`
}

type skillFileName string

const (
	skillFileNameStandard skillFileName = "SKILL.md"
	skillFileNameMarkdown skillFileName = ".md"
	skillFileNameCursor   skillFileName = ".mdc"
)

type skillAgentDefinition struct {
	ID            string
	Aliases       []string
	ProjectRelDir string
	UserRelDir    string
	FileName      skillFileName
}

var skillAgentDefinitions = []skillAgentDefinition{
	{ID: "claude", Aliases: []string{"claude-code"}, ProjectRelDir: filepath.Join(".claude", "skills"), UserRelDir: filepath.Join(".claude", "skills"), FileName: skillFileNameStandard},
	{ID: "codex", ProjectRelDir: filepath.Join(".agents", "skills"), UserRelDir: filepath.Join(".agents", "skills"), FileName: skillFileNameStandard},
	{ID: "gemini", Aliases: []string{"gemini-cli"}, ProjectRelDir: filepath.Join(".gemini", "skills"), UserRelDir: filepath.Join(".gemini", "skills"), FileName: skillFileNameStandard},
	{ID: "opencode", ProjectRelDir: filepath.Join(".opencode", "skills"), UserRelDir: filepath.Join(".config", "opencode", "skills"), FileName: skillFileNameStandard},
	{ID: "cursor", ProjectRelDir: filepath.Join(".cursor", "skills"), UserRelDir: filepath.Join(".cursor", "skills"), FileName: skillFileNameCursor},
	{ID: "github-copilot", ProjectRelDir: filepath.Join(".github", "skills"), UserRelDir: filepath.Join(".github", "skills"), FileName: skillFileNameMarkdown},
	{ID: "windsurf", ProjectRelDir: filepath.Join(".windsurf", "skills"), UserRelDir: filepath.Join(".windsurf", "skills"), FileName: skillFileNameMarkdown},
	{ID: "antigravity", ProjectRelDir: filepath.Join(".antigravity", "skills"), UserRelDir: filepath.Join(".antigravity", "skills"), FileName: skillFileNameStandard},
	{ID: "amp", ProjectRelDir: filepath.Join(".amp", "skills"), UserRelDir: filepath.Join(".amp", "skills"), FileName: skillFileNameStandard},
	{ID: "clawdbot", ProjectRelDir: filepath.Join(".clawdbot", "skills"), UserRelDir: filepath.Join(".clawdbot", "skills"), FileName: skillFileNameStandard},
	{ID: "factory", Aliases: []string{"droid"}, ProjectRelDir: filepath.Join(".factory", "skills"), UserRelDir: filepath.Join(".factory", "skills"), FileName: skillFileNameStandard},
	{ID: "goose", ProjectRelDir: filepath.Join(".goose", "skills"), UserRelDir: filepath.Join(".goose", "skills"), FileName: skillFileNameStandard},
	{ID: "kilo-code", ProjectRelDir: filepath.Join(".kilocode", "skills"), UserRelDir: filepath.Join(".kilocode", "skills"), FileName: skillFileNameStandard},
	{ID: "kiro-cli", ProjectRelDir: filepath.Join(".kiro", "skills"), UserRelDir: filepath.Join(".kiro", "skills"), FileName: skillFileNameStandard},
	{ID: "roo-code", ProjectRelDir: filepath.Join(".roo", "skills"), UserRelDir: filepath.Join(".roo", "skills"), FileName: skillFileNameStandard},
	{ID: "trae", ProjectRelDir: filepath.Join(".trae", "skills"), UserRelDir: filepath.Join(".trae", "skills"), FileName: skillFileNameStandard},
	{ID: "cline", ProjectRelDir: filepath.Join(".cline", "skills"), UserRelDir: filepath.Join(".cline", "skills"), FileName: skillFileNameStandard},
	{ID: "codebuddy", ProjectRelDir: filepath.Join(".codebuddy", "skills"), UserRelDir: filepath.Join(".codebuddy", "skills"), FileName: skillFileNameStandard},
	{ID: "commandcode", ProjectRelDir: filepath.Join(".commandcode", "skills"), UserRelDir: filepath.Join(".commandcode", "skills"), FileName: skillFileNameStandard},
	{ID: "continue", ProjectRelDir: filepath.Join(".continue", "skills"), UserRelDir: filepath.Join(".continue", "skills"), FileName: skillFileNameStandard},
	{ID: "crush", ProjectRelDir: filepath.Join(".crush", "skills"), UserRelDir: filepath.Join(".crush", "skills"), FileName: skillFileNameStandard},
	{ID: "mcpjam", ProjectRelDir: filepath.Join(".mcpjam", "skills"), UserRelDir: filepath.Join(".mcpjam", "skills"), FileName: skillFileNameStandard},
	{ID: "mux", ProjectRelDir: filepath.Join(".mux", "skills"), UserRelDir: filepath.Join(".mux", "skills"), FileName: skillFileNameStandard},
	{ID: "neovate", ProjectRelDir: filepath.Join(".neovate", "skills"), UserRelDir: filepath.Join(".neovate", "skills"), FileName: skillFileNameStandard},
	{ID: "openhands", ProjectRelDir: filepath.Join(".openhands", "skills"), UserRelDir: filepath.Join(".openhands", "skills"), FileName: skillFileNameStandard},
	{ID: "pi", ProjectRelDir: filepath.Join(".pi", "skills"), UserRelDir: filepath.Join(".pi", "skills"), FileName: skillFileNameStandard},
	{ID: "qoder", ProjectRelDir: filepath.Join(".qoder", "skills"), UserRelDir: filepath.Join(".qoder", "skills"), FileName: skillFileNameStandard},
	{ID: "qwen", ProjectRelDir: filepath.Join(".qwen", "skills"), UserRelDir: filepath.Join(".qwen", "skills"), FileName: skillFileNameStandard},
	{ID: "vercel", ProjectRelDir: filepath.Join(".vercel", "skills"), UserRelDir: filepath.Join(".vercel", "skills"), FileName: skillFileNameStandard},
	{ID: "zencoder", ProjectRelDir: filepath.Join(".zencoder", "skills"), UserRelDir: filepath.Join(".zencoder", "skills"), FileName: skillFileNameStandard},
	{ID: "devin", ProjectRelDir: filepath.Join(".devin", "skills"), UserRelDir: filepath.Join(".devin", "skills"), FileName: skillFileNameMarkdown},
	{ID: "aider", ProjectRelDir: filepath.Join(".aider", "skills"), UserRelDir: filepath.Join(".aider", "skills"), FileName: skillFileNameStandard},
	{ID: "sourcegraph-cody", ProjectRelDir: filepath.Join(".cody", "skills"), UserRelDir: filepath.Join(".cody", "skills"), FileName: skillFileNameStandard},
	{ID: "amazon-q", ProjectRelDir: filepath.Join(".amazonq", "skills"), UserRelDir: filepath.Join(".amazonq", "skills"), FileName: skillFileNameStandard},
	{ID: "augment-code", ProjectRelDir: filepath.Join(".augment", "skills"), UserRelDir: filepath.Join(".augment", "skills"), FileName: skillFileNameStandard},
	{ID: "replit-agent", ProjectRelDir: filepath.Join(".replit", "skills"), UserRelDir: filepath.Join(".replit", "skills"), FileName: skillFileNameMarkdown},
	{ID: "bolt", ProjectRelDir: filepath.Join(".bolt", "skills"), UserRelDir: filepath.Join(".bolt", "skills"), FileName: skillFileNameMarkdown},
	{ID: "lovable", ProjectRelDir: filepath.Join(".lovable", "skills"), UserRelDir: filepath.Join(".lovable", "skills"), FileName: skillFileNameMarkdown},
	{ID: "tabby", ProjectRelDir: filepath.Join(".tabby", "skills"), UserRelDir: filepath.Join(".tabby", "skills"), FileName: skillFileNameStandard},
	{ID: "tabnine", ProjectRelDir: filepath.Join(".tabnine", "skills"), UserRelDir: filepath.Join(".tabnine", "skills"), FileName: skillFileNameStandard},
	{ID: "codegpt", ProjectRelDir: filepath.Join(".codegpt", "skills"), UserRelDir: filepath.Join(".codegpt", "skills"), FileName: skillFileNameStandard},
	{ID: "playcode-agent", ProjectRelDir: filepath.Join(".playcode", "skills"), UserRelDir: filepath.Join(".playcode", "skills"), FileName: skillFileNameMarkdown},
	{ID: "universal", ProjectRelDir: "skills", UserRelDir: "skills", FileName: skillFileNameStandard},
}

func newSkillCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "skill",
		Short: "Skill management commands",
	}

	cmd.AddCommand(newSkillCreateCmd())
	cmd.AddCommand(newSkillValidateCmd())

	return cmd
}

func newSkillValidateCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "validate",
		Short: "Validate skill documentation quality",
		RunE: func(cmd *cobra.Command, args []string) error {
			reports, err := validateProjectSkills()
			if err != nil {
				return fmt.Errorf("cli.newSkillValidateCmd: %w", err)
			}
			if jsonOutput {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(reports)
			}
			for _, report := range reports {
				if _, err := fmt.Fprintf(cmd.OutOrStdout(), "%s\t%s\n", strings.ToUpper(report.Status), report.Path); err != nil {
					return fmt.Errorf("cli.newSkillValidateCmd: write report: %w", err)
				}
				for _, issue := range report.Issues {
					if _, err := fmt.Fprintf(cmd.OutOrStdout(), "  - %s\n", issue); err != nil {
						return fmt.Errorf("cli.newSkillValidateCmd: write issue: %w", err)
					}
				}
			}
			return nil
		},
	}
}

func newSkillCreateCmd() *cobra.Command {
	var scope string
	var agentType string
	var description string

	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create a skill file for an AI coding agent",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			name := args[0]
			if err := validateSkillName(name); err != nil {
				return commandError("cli.newSkillCreateCmd", err)
			}

			targets, err := resolveSkillTargets(scope, agentType, name)
			if err != nil {
				return fmt.Errorf("cli.newSkillCreateCmd: resolve targets: %w", err)
			}

			desc := description
			if desc == "" {
				desc = defaultSkillDescription
			}

			for _, target := range targets {
				if err := writeSkillFile(target.Path, renderSkillContent(name, desc), writeModeCreate); err != nil {
					return fmt.Errorf("cli.newSkillCreateCmd: write %s skill: %w", target.Agent, err)
				}
			}

			if jsonOutput {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(map[string]any{
					"name":        name,
					"scope":       scope,
					"description": desc,
					"targets":     targets,
				})
			}

			for _, target := range targets {
				if _, err := fmt.Fprintf(cmd.OutOrStdout(), "generated %s skill at %s\n", target.Agent, target.Path); err != nil {
					return fmt.Errorf("cli.newSkillCreateCmd: write output: %w", err)
				}
			}

			return nil
		},
	}

	f := cmd.Flags()
	f.StringVar(&scope, "scope", "project", "Skill scope: project|user")
	f.StringVar(&agentType, "agent", "all", "Target agent identifier or all")
	f.StringVar(&description, "description", "", "Skill description")

	return cmd
}

func validateSkillName(name string) error {
	if !skillNamePattern.MatchString(name) {
		return newUserError(
			fmt.Sprintf("Skill name %q is invalid", name),
			"Skill names may use only lowercase letters, numbers, and single hyphens.",
			"Rename it like `my-skill` and re-run `agentcom skill create <name>`.",
		)
	}
	return nil
}

func resolveSkillTargets(scope string, agentType string, name string) ([]skillTarget, error) {
	agents, err := resolveSkillAgents(agentType)
	if err != nil {
		return nil, err
	}

	return resolveSkillTargetsForAgents(scope, agents, name)
}

func resolveTemplateSkillTargets(scope string, name string) ([]skillTarget, error) {
	return resolveTemplateSkillTargetsForSelectedAgents(scope, name, nil)
}

func resolveTemplateSkillTargetsForSelectedAgents(scope string, name string, selectedAgents []string) ([]skillTarget, error) {
	agents := append([]string(nil), selectedAgents...)
	if len(agents) == 0 {
		agents = []string{"claude", "codex", "gemini", "opencode"}
	}
	return resolveSkillTargetsForAgents(scope, agents, name)
}

func resolveSkillTargetsForAgents(scope string, agents []string, name string) ([]skillTarget, error) {
	targets := make([]skillTarget, 0, len(agents))
	for _, agent := range agents {
		targetPath, err := skillTargetPath(scope, agent, name)
		if err != nil {
			return nil, err
		}
		targets = append(targets, skillTarget{Agent: agent, Path: targetPath})
	}

	sort.Slice(targets, func(i, j int) bool {
		return targets[i].Agent < targets[j].Agent
	})

	return targets, nil
}

func resolveSkillBaseDir(scope string) (string, error) {
	switch scope {
	case "project":
		cwd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("getwd: %w", err)
		}
		return cwd, nil
	case "user":
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("user home: %w", err)
		}
		return home, nil
	default:
		return "", fmt.Errorf("invalid scope %q: must be project or user", scope)
	}
}

func resolveSkillAgents(agentType string) ([]string, error) {
	if agentType == "all" {
		agents := make([]string, 0, len(skillAgentDefinitions))
		for _, definition := range skillAgentDefinitions {
			agents = append(agents, definition.ID)
		}
		return agents, nil
	}

	definition, ok := findSkillAgentDefinition(agentType)
	if !ok {
		return nil, fmt.Errorf("invalid agent %q: must be one of %s, or all", agentType, strings.Join(validSkillAgentNames(), ", "))
	}

	return []string{definition.ID}, nil
}

func skillTargetPath(scope string, agent string, name string) (string, error) {
	baseDir, err := resolveSkillBaseDir(scope)
	if err != nil {
		return "", err
	}

	definition, ok := findSkillAgentDefinition(agent)
	if !ok {
		return "", fmt.Errorf("unsupported agent %q", agent)
	}

	relDir := definition.ProjectRelDir
	if scope == "user" {
		relDir = definition.UserRelDir
	}

	return filepath.Join(baseDir, relDir, skillFileRelativePath(definition.FileName, name)), nil
}

func findSkillAgentDefinition(agent string) (skillAgentDefinition, bool) {
	for _, definition := range skillAgentDefinitions {
		if definition.ID == agent {
			return definition, true
		}
		for _, alias := range definition.Aliases {
			if alias == agent {
				return definition, true
			}
		}
	}

	return skillAgentDefinition{}, false
}

func validSkillAgentNames() []string {
	names := make([]string, 0, len(skillAgentDefinitions))
	for _, definition := range skillAgentDefinitions {
		names = append(names, definition.ID)
		names = append(names, definition.Aliases...)
	}
	sort.Strings(names)
	return names
}

func skillFileRelativePath(fileName skillFileName, skillName string) string {
	switch fileName {
	case skillFileNameMarkdown, skillFileNameCursor:
		return skillName + string(fileName)
	default:
		return filepath.Join(skillName, string(skillFileNameStandard))
	}
}

func writeSkillFile(path string, content string, mode writeMode) error {
	markerContent := wrapWithMarkers(content)
	exists := false
	if _, err := os.Stat(path); err == nil {
		exists = true
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("cli.writeSkillFile: stat: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("cli.writeSkillFile: mkdir: %w", err)
	}

	if !exists {
		if err := os.WriteFile(path, []byte(markerContent), 0o644); err != nil {
			return fmt.Errorf("cli.writeSkillFile: write: %w", err)
		}
		return nil
	}

	switch mode {
	case writeModeOverwrite:
		if err := os.WriteFile(path, []byte(markerContent), 0o644); err != nil {
			return fmt.Errorf("cli.writeSkillFile: overwrite: %w", err)
		}
		return nil
	case writeModeAppend:
		existing, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("cli.writeSkillFile: read existing: %w", err)
		}
		existingStr := string(existing)
		_, _, found := findMarkerBounds(existingStr)
		result := appendMarkerBlock(existingStr, markerContent)
		if found {
			slog.Debug("updating existing agentcom marker block", "path", path)
			result = replaceMarkerBlock(existingStr, markerContent)
		} else {
			slog.Debug("appending agentcom configuration to existing file", "path", path)
		}
		if err := os.WriteFile(path, []byte(result), 0o644); err != nil {
			return fmt.Errorf("cli.writeSkillFile: write append result: %w", err)
		}
		return nil
	default:
		return newUserError(
			fmt.Sprintf("Skill file already exists at %s", path),
			"Create mode never overwrites an existing skill file.",
			"Re-run with `--force` or choose a different skill name.",
		)
	}
}

func renderSkillContent(name string, description string) string {
	bodyTitle := titleWords(strings.ReplaceAll(name, "-", " "))
	return fmt.Sprintf(`---
name: %s
description: %s
---

# %s

Add your skill instructions here.
`, name, description, bodyTitle)
}

func titleWords(s string) string {
	parts := strings.Fields(s)
	for i, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		for j := 1; j < len(runes); j++ {
			runes[j] = unicode.ToLower(runes[j])
		}
		parts[i] = string(runes)
	}
	return strings.Join(parts, " ")
}

func validateProjectSkills() ([]skillValidationReport, error) {
	projectDir, err := os.Getwd()
	if err != nil {
		return nil, fmt.Errorf("getwd: %w", err)
	}
	reports := make([]skillValidationReport, 0)
	err = filepath.WalkDir(projectDir, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Base(path) != "SKILL.md" {
			return nil
		}
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		reports = append(reports, validateSkillFile(path, string(content)))
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk skills: %w", err)
	}
	sort.Slice(reports, func(i, j int) bool { return reports[i].Path < reports[j].Path })
	return reports, nil
}

func validateSkillFile(path string, content string) skillValidationReport {
	report := skillValidationReport{Path: path, Status: "pass"}
	checks := make([]string, 0, 4)
	issues := make([]string, 0, 4)
	lineCount := len(strings.Split(content, "\n"))
	shared := isSharedSkillPath(path)
	minLines := 50
	if shared {
		minLines = 60
	}
	if lineCount >= minLines {
		checks = append(checks, fmt.Sprintf("line_count>=%d", minLines))
	} else {
		issues = append(issues, fmt.Sprintf("line count %d is below %d", lineCount, minLines))
	}

	requiredSections := []string{"## Communication"}
	if shared {
		requiredSections = append(requiredSections, "## Lifecycle")
	} else {
		requiredSections = append(requiredSections, "## Workflow")
	}
	missingSections := make([]string, 0)
	for _, section := range requiredSections {
		if !strings.Contains(content, section) {
			missingSections = append(missingSections, section)
		}
	}
	if len(missingSections) == 0 {
		checks = append(checks, "required_sections")
	} else {
		issues = append(issues, fmt.Sprintf("missing sections: %s", strings.Join(missingSections, ", ")))
	}

	placeholders := []string{"<sender>", "<target>", "<name>"}
	foundPlaceholders := make([]string, 0)
	for _, placeholder := range placeholders {
		if strings.Contains(content, placeholder) {
			foundPlaceholders = append(foundPlaceholders, placeholder)
		}
	}
	if len(foundPlaceholders) == 0 {
		checks = append(checks, "no_placeholders")
	} else {
		issues = append(issues, fmt.Sprintf("contains placeholders: %s", strings.Join(foundPlaceholders, ", ")))
	}

	if strings.Contains(content, "agentcom ") {
		checks = append(checks, "cli_examples")
	} else {
		issues = append(issues, "missing agentcom CLI examples")
	}

	if len(issues) > 0 {
		report.Status = "fail"
		report.Issues = issues
	} else {
		report.Checks = checks
	}
	return report
}

func isSharedSkillPath(path string) bool {
	clean := filepath.ToSlash(path)
	return strings.HasSuffix(clean, "/agentcom/SKILL.md")
}
