package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"github.com/spf13/cobra"
)

const defaultSkillDescription = "Skill generated by agentcom"

var skillNamePattern = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

type skillTarget struct {
	Agent string `json:"agent"`
	Path  string `json:"path"`
}

func newSkillCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "skill",
		Short: "Skill management commands",
	}

	cmd.AddCommand(newSkillCreateCmd())

	return cmd
}

func newSkillCreateCmd() *cobra.Command {
	var scope string
	var agentType string
	var description string

	cmd := &cobra.Command{
		Use:   "create <name>",
		Short: "Create a skill file for an AI coding agent",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			name := args[0]
			if err := validateSkillName(name); err != nil {
				return fmt.Errorf("cli.newSkillCreateCmd: %w", err)
			}

			targets, err := resolveSkillTargets(scope, agentType, name)
			if err != nil {
				return fmt.Errorf("cli.newSkillCreateCmd: resolve targets: %w", err)
			}

			desc := description
			if desc == "" {
				desc = defaultSkillDescription
			}

			for _, target := range targets {
				if err := writeSkillFile(target.Path, renderSkillContent(name, desc)); err != nil {
					return fmt.Errorf("cli.newSkillCreateCmd: write %s skill: %w", target.Agent, err)
				}
			}

			if jsonOutput {
				enc := json.NewEncoder(cmd.OutOrStdout())
				enc.SetIndent("", "  ")
				return enc.Encode(map[string]any{
					"name":        name,
					"scope":       scope,
					"description": desc,
					"targets":     targets,
				})
			}

			for _, target := range targets {
				if _, err := fmt.Fprintf(cmd.OutOrStdout(), "generated %s skill at %s\n", target.Agent, target.Path); err != nil {
					return fmt.Errorf("cli.newSkillCreateCmd: write output: %w", err)
				}
			}

			return nil
		},
	}

	f := cmd.Flags()
	f.StringVar(&scope, "scope", "project", "Skill scope: project|user")
	f.StringVar(&agentType, "agent", "all", "Target agent: claude|codex|gemini|opencode|all")
	f.StringVar(&description, "description", "", "Skill description")

	return cmd
}

func validateSkillName(name string) error {
	if !skillNamePattern.MatchString(name) {
		return fmt.Errorf("invalid skill name %q: use lowercase letters, numbers, and single hyphens only", name)
	}
	return nil
}

func resolveSkillTargets(scope string, agentType string, name string) ([]skillTarget, error) {
	agents, err := resolveSkillAgents(agentType)
	if err != nil {
		return nil, err
	}

	targets := make([]skillTarget, 0, len(agents))
	for _, agent := range agents {
		targetPath, err := skillTargetPath(scope, agent, name)
		if err != nil {
			return nil, err
		}
		targets = append(targets, skillTarget{
			Agent: agent,
			Path:  targetPath,
		})
	}

	sort.Slice(targets, func(i, j int) bool {
		return targets[i].Agent < targets[j].Agent
	})

	return targets, nil
}

func resolveSkillBaseDir(scope string) (string, error) {
	switch scope {
	case "project":
		cwd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("getwd: %w", err)
		}
		return cwd, nil
	case "user":
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("user home: %w", err)
		}
		return home, nil
	default:
		return "", fmt.Errorf("invalid scope %q: must be project or user", scope)
	}
}

func resolveSkillAgents(agentType string) ([]string, error) {
	switch agentType {
	case "all":
		return []string{"claude", "codex", "gemini", "opencode"}, nil
	case "claude", "codex", "gemini", "opencode":
		return []string{agentType}, nil
	default:
		return nil, fmt.Errorf("invalid agent %q: must be claude, codex, gemini, opencode, or all", agentType)
	}
}

func skillTargetPath(scope string, agent string, name string) (string, error) {
	baseDir, err := resolveSkillBaseDir(scope)
	if err != nil {
		return "", err
	}

	var relDir string
	switch agent {
	case "claude":
		relDir = filepath.Join(".claude", "skills")
	case "codex":
		relDir = filepath.Join(".agents", "skills")
	case "gemini":
		relDir = filepath.Join(".gemini", "skills")
	case "opencode":
		if scope == "project" {
			relDir = filepath.Join(".opencode", "skills")
		} else {
			relDir = filepath.Join(".config", "opencode", "skills")
		}
	default:
		return "", fmt.Errorf("unsupported agent %q", agent)
	}

	return filepath.Join(baseDir, relDir, name, "SKILL.md"), nil
}

func writeSkillFile(path string, content string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("SKILL.md already exists: %s", path)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat SKILL.md: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir skill dir: %w", err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write SKILL.md: %w", err)
	}

	return nil
}

func renderSkillContent(name string, description string) string {
	bodyTitle := titleWords(strings.ReplaceAll(name, "-", " "))
	return fmt.Sprintf(`---
name: %s
description: %s
---

# %s

Add your skill instructions here.
`, name, description, bodyTitle)
}

func titleWords(s string) string {
	parts := strings.Fields(s)
	for i, part := range parts {
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		runes[0] = unicode.ToUpper(runes[0])
		for j := 1; j < len(runes); j++ {
			runes[j] = unicode.ToLower(runes[j])
		}
		parts[i] = string(runes)
	}
	return strings.Join(parts, " ")
}
